Repository Darleanow/task-manager-low, pull requests merged in 2023-12, with the labels that each got.

#17 Frontend/feature/secured routing
  package-lock.json
  package.json
  src/App.js
  src/AuthentPage/AuthentPage.js
  src/ProjectPage/ProjectPage.js
  src/TasksPage/TasksPage.js
  src/Utils/Routing/ProtectedRoute.js
  src/Utils/Routing/store.js
  src/index.js
Labels: enhancement

#25 Fullstack/feature/enhance security and storage
  Backend/models/userModels.js
  package-lock.json
  package.json
  src/AuthentPage/AuthenPage.scss
  src/AuthentPage/AuthentPage.js
  src/ProjectPage/ProjectPage.js
  src/Utils/BulkUtilsImport.js
  src/Utils/Routing/store.js
  src/Utils/Routing/token.js
Labels: bug, enhancement

#30 Authent/feature/persist login
  package-lock.json
  package.json
  src/App.js
  src/Utils/Routing/store.js
Labels: bug, enhancement

#31 Fullstack/feature/project mapping to tasks
  Backend/app.js
  Backend/logic.sql
  Backend/models/taskModels.js
  Backend/routes/taskRoutes.js
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/AuthentPage/AuthentPage.js
  src/Components/BoardList/BoardList.js
  src/Components/BoardList/BoardList.scss
  src/Components/Card/Card.js
  src/Components/Card/Card.scss
  src/Components/PrimaryMenuBar/PrimaryMenuBar.scss
  src/Components/SecondaryMenuBar/SecondaryMenuBar.js
  src/Components/SecondaryMenuBar/SecondaryMenuBar.scss
  src/ProjectPage/Components/ProjectList/ProjectList.js
  src/TasksPage/Components/RichText.js
  src/TasksPage/Components/RichText.scss
  src/TasksPage/Components/TaskCreation/TaskCreation.js
  src/TasksPage/TasksPage.js
  src/TasksPage/TasksPage.scss
  src/Utils/Routing/store.js
  src/index.scss
Labels: bug, enhancement

#35 Nouveau script sql
  Backend/logic.sql
Labels: bug, back-end

#36 Feature/fix bugs
  src/Components/BoardList/BoardList.js
  src/Components/Card/Card.js
  src/Components/PrimaryMenuBar/PrimaryMenuBar.js
  src/Components/SlidingMenuBar/Navbar.js
  src/Components/SlidingMenuBar/Navbar.scss
  src/ProjectPage/Components/ProjectList/ProjectList.js
  src/TasksPage/Components/RichText.scss
  src/TasksPage/Components/TaskCreation/TaskCreation.js
  src/TasksPage/Components/TaskCreation/TaskCreation.scss
  src/TasksPage/TasksPage.js
  src/TasksPage/TasksPage.scss
  src/Utils/Misc/ToastsTools.js
Labels: bug, enhancement, ux-ui
